version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:s
      - ./frontend:/app
